name 'cloudsmith-federated_wiki'
version '0.1.0'

author 'Cloudsmith Inc.'
license 'Apache License 2.0'
project_page ''
source ''
summary 'Module handling Smallest-Federated-Wiki and its gem dependencies'
description ''

dependency 'cloudsmith/apache2', '>=0.1.0'
dependency 'cloudsmith/passenger', '>=0.1.0'
dependency 'cloudsmith/rubygems19', '>=0.1.0'
dependency 'cloudsmith/memcached', '>=0.1.0'
