name 'cloudsmith-rubygems19'
version '0.1.0'

author 'Cloudsmith Inc.'
license 'Apache License 2.0'
project_page ''
source ''
summary 'Module handling installation and updating of the ruby gem system'
description ''
